11:45:59.498 Running build in Washington, D.C., USA (East) – iad1
11:45:59.499 Build machine configuration: 2 cores, 8 GB
11:45:59.617 Cloning github.com/amitdevx/v0-le-lo-saa-s-landing-jy (Branch: v0/uffamit-280c31ee, Commit: e23b03d)
11:45:59.951 Cloning completed: 333.000ms
11:46:01.366 Restored build cache from previous deployment (J9yf3nAzvT1eA4vzto63b2igGpYp)
11:46:01.741 Running "vercel build"
11:46:02.692 Vercel CLI 50.11.0
11:46:03.031 Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
11:46:03.031 Using pnpm@10.x based on project creation date
11:46:03.032 To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
11:46:03.070 Installing dependencies...
11:46:03.819 Lockfile is up to date, resolution step is skipped
11:46:04.012 Already up to date
11:46:04.524 
11:46:04.553 Done in 1.3s using pnpm v10.28.0
11:46:04.566 Detected Next.js version: 14.2.25
11:46:04.592 Running "pnpm run build"
11:46:04.892 
11:46:04.893 > my-v0-project@0.1.0 build /vercel/path0
11:46:04.894 > next build
11:46:04.894 
11:46:05.624   ▲ Next.js 14.2.25
11:46:05.625 
11:46:05.646    Creating an optimized production build ...
11:46:11.908 Failed to compile.
11:46:11.909 
11:46:11.910 ./app/dashboard/analysis/page.tsx
11:46:11.910 Error: 
11:46:11.910   [31mx[0m Unexpected token `DashboardLayout`. Expected jsx identifier
11:46:11.910     ,-[[36;1;4m/vercel/path0/app/dashboard/analysis/page.tsx[0m:41:1]
11:46:11.911  [2m41[0m |   ) || []
11:46:11.911  [2m42[0m | 
11:46:11.912  [2m43[0m |   return (
11:46:11.912  [2m44[0m |     <DashboardLayout>
11:46:11.912     : [31;1m     ^^^^^^^^^^^^^^^[0m
11:46:11.912  [2m45[0m |       <div>
11:46:11.912  [2m46[0m |         <Breadcrumb items={[{ label: "Analysis" }]} />
11:46:11.912     `----
11:46:11.912 
11:46:11.912 Caused by:
11:46:11.913     Syntax Error
11:46:11.913 
11:46:11.913 Import trace for requested module:
11:46:11.913 ./app/dashboard/analysis/page.tsx
11:46:11.913 
11:46:11.913 ./app/dashboard/billing/page.tsx
11:46:11.913 Error: 
11:46:11.913   [31mx[0m Unexpected token `DashboardLayout`. Expected jsx identifier
11:46:11.913     ,-[[36;1;4m/vercel/path0/app/dashboard/billing/page.tsx[0m:12:1]
11:46:11.913  [2m12[0m | 
11:46:11.913  [2m13[0m | export default function BillingPage() {
11:46:11.913  [2m14[0m |   return (
11:46:11.913  [2m15[0m |     <DashboardLayout>
11:46:11.913     : [31;1m     ^^^^^^^^^^^^^^^[0m
11:46:11.913  [2m16[0m |       <div>
11:46:11.913  [2m17[0m |         <Breadcrumb items={[{ label: "Billing" }]} />
11:46:11.913     `----
11:46:11.913 
11:46:11.913 Caused by:
11:46:11.914     Syntax Error
11:46:11.914 
11:46:11.914 Import trace for requested module:
11:46:11.914 ./app/dashboard/billing/page.tsx
11:46:11.914 
11:46:11.914 ./app/dashboard/chat/page.tsx
11:46:11.914 Error: 
11:46:11.914   [31mx[0m Unexpected token `DashboardLayout`. Expected jsx identifier
11:46:11.914     ,-[[36;1;4m/vercel/path0/app/dashboard/chat/page.tsx[0m:82:1]
11:46:11.914  [2m82[0m |   }
11:46:11.914  [2m83[0m | 
11:46:11.914  [2m84[0m |   return (
11:46:11.914  [2m85[0m |     <DashboardLayout>
11:46:11.914     : [31;1m     ^^^^^^^^^^^^^^^[0m
11:46:11.914  [2m86[0m |       <div>
11:46:11.914  [2m87[0m |         <Breadcrumb items={[{ label: "Chat" }]} />
11:46:11.914     `----
11:46:11.914 
11:46:11.914 Caused by:
11:46:11.915     Syntax Error
11:46:11.915 
11:46:11.915 Import trace for requested module:
11:46:11.915 ./app/dashboard/chat/page.tsx
11:46:11.915 
11:46:11.915 ./app/dashboard/exports/page.tsx
11:46:11.915 Error: 
11:46:11.915   [31mx[0m Unexpected token `DashboardLayout`. Expected jsx identifier
11:46:11.915     ,-[[36;1;4m/vercel/path0/app/dashboard/exports/page.tsx[0m:42:1]
11:46:11.915  [2m42[0m | 
11:46:11.915  [2m43[0m | export default function ExportsPage() {
11:46:11.915  [2m44[0m |   return (
11:46:11.915  [2m45[0m |     <DashboardLayout>
11:46:11.915     : [31;1m     ^^^^^^^^^^^^^^^[0m
11:46:11.915  [2m46[0m |       <div>
11:46:11.915  [2m47[0m |         <Breadcrumb items={[{ label: "Exports" }]} />
11:46:11.915     `----
11:46:11.915 
11:46:11.915 Caused by:
11:46:11.915     Syntax Error
11:46:11.915 
11:46:11.915 Import trace for requested module:
11:46:11.915 ./app/dashboard/exports/page.tsx
11:46:11.916 
11:46:11.916 ./app/dashboard/profile/page.tsx
11:46:11.916 Error: 
11:46:11.916   [31mx[0m Unexpected token `DashboardLayout`. Expected jsx identifier
11:46:11.916     ,-[[36;1;4m/vercel/path0/app/dashboard/profile/page.tsx[0m:21:1]
11:46:11.916  [2m21[0m |   }
11:46:11.916  [2m22[0m | 
11:46:11.916  [2m23[0m |   return (
11:46:11.916  [2m24[0m |     <DashboardLayout>
11:46:11.916     : [31;1m     ^^^^^^^^^^^^^^^[0m
11:46:11.916  [2m25[0m |       <div>
11:46:11.916  [2m26[0m |         <Breadcrumb items={[{ label: "Profile" }]} />
11:46:11.916     `----
11:46:11.916 
11:46:11.916 Caused by:
11:46:11.916     Syntax Error
11:46:11.916 
11:46:11.916 Import trace for requested module:
11:46:11.916 ./app/dashboard/profile/page.tsx
11:46:11.916 
11:46:11.930 
11:46:11.932 > Build failed because of webpack errors
11:46:11.959  ELIFECYCLE  Command failed with exit code 1.
11:46:11.979 Error: Command "pnpm run build" exited with 1